---
output:
  pdf_document: default
urlcolor: blue
header-includes:    
  - \usepackage{lastpage}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[CO, CE]{Shiqi Liu, 1004743646}
  - \fancyfoot[CO, CE]{\thepage \ of \pageref{LastPage}}
---

```{r setup, message = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk.

# These are the packages you will need for this activity
packages_needed <- c("tidyverse", "googledrive", "readxl", "janitor", 
                     "lubridate", "opendatatoronto", "ggthemes")

package.check <- lapply(
  packages_needed,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
    }
  }
)

# Credit: package.check based on a helpful post from Vikram Baliga https://vbaliga.github.io/verify-that-r-packages-are-installed-and-loaded/

# Load tidyverse
library(tidyverse)
library(readxl)
library(janitor)
library(opendatatoronto)
library(ggthemes)

# Set so that long lines in R will be wrapped:
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), echo = FALSE)
```


```{r getdata, eval = FALSE, echo=FALSE}
# Students: You probably shouldn't change any of the code in this chunk BUT...

# This chunk loads the most recent data from Toronto City and the data from OpenToronto.

# You have to RUN this chunk by hand to update the data as 
#   eval is set to FALSE to limit unnecessary requsts on the site.

###################################################
# Step one: Get the COVID data from Toronto City. #
###################################################

#googledrive::drive_deauth()

#url1 <- "https://drive.google.com/file/d/11KF1DuN5tntugNc10ogQDzFnW05ruzLH/view"
#googledrive::drive_download(url1, path="data/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx", overwrite = TRUE)

#url2 <- "https://drive.google.com/file/d/1jzH64LvFQ-UsDibXO0MOtvjbL2CvnV3N/view"
#googledrive::drive_download(url2, path = "data/CityofToronto_COVID-19_NeighbourhoodData.xlsx", overwrite = TRUE)

# this removes the url object that we don't need anymore
#rm(url1, url2)

#####################################################################
# Step two: Get the data neighbourhood data from Open Data Toronto. #
#####################################################################

nbhoods_shape_raw <- list_package_resources("neighbourhoods") %>% 
  get_resource()

# I downloaded the data as of Jan 31, 2021, since the website won't allow us to get the most updated data
saveRDS(nbhoods_shape_raw, "/Users/liushiqi/Desktop/STA303/Data Exploration/neighbourhood_shapefile.Rds")

nbhood_profile <- search_packages("Neighbourhood Profile") %>%
  list_package_resources() %>% 
  filter(name == "neighbourhood-profiles-2016-csv") %>% 
  get_resource()

saveRDS(nbhood_profile, "data/neighbourhood_profile.Rds")
```


```{r load_data, echo=FALSE}
######################################################
# Step three: Load the COVID data from Toronto City. #
######################################################

# Saving the name of the file as an object and then using the object name in the
# following code is a helpful practice. Why? If we change the name of the file 
# being used, we'll only have to change it in one place. This helps us avoid 
# 'human error'.

# I downloaded the data as of Jan 31, 2021, since the website won't allow us to get the most updated data
daily_data <- "/Users/liushiqi/Desktop/STA303/Data Exploration/CityofToronto_COVID-19_Daily_Public_Reporting.xlsx"

# Cases reported by date
reported_raw <- read_excel(daily_data, sheet = 5) %>% 
  clean_names()

# Cases by outbreak type
outbreak_raw <- read_excel(daily_data, sheet = 3) %>% 
  clean_names()

# When was this data updated?
date_daily <- read_excel(daily_data, sheet = 1) %>% 
  clean_names()

# By neighbourhood
neighbourood_data <- "/Users/liushiqi/Desktop/STA303/Data Exploration/CityofToronto_COVID-19_NeighbourhoodData.xlsx"

# Cases reported by date
nbhood_raw <- read_excel(neighbourood_data, sheet = 2) %>% 
  clean_names()

# Date the neighbourhood data was last updated
date_nbhood <- read_excel(neighbourood_data, sheet = 1) %>% 
  clean_names()

#don't need these anymore
rm(daily_data, neighbourood_data)

#############################################################
# Step four: Load the neighbourhood data from Toronto City. #
#############################################################

# Get neighbourhood profile data
nbhood_profile <- readRDS("data/neighbourhood_profile.Rds")

# Get shape data for mapping 
nbhoods_shape_raw <- readRDS("data/neighbourhood_shapefile.Rds") %>% 
  sf::st_as_sf() ## Makes sure shape info is in the most up to date format

```

Code last run `r Sys.Date()`.  
Daily: `r date_daily[1,1]`.   
Neighbourhood: `r date_nbhood[1,1]`. 

# Task 1: Daily cases
## Data wrangling

```{r cases_dw, echo=TRUE}
reported <- reported_raw %>%
  mutate_if(is.numeric, replace_na, replace = 0) 
# Replace all NA values with 0 in the recovered, active and deceased columns
reported$reported_date <- date(reported$reported_date) 
# To format the reported_data column into the date format
reported_long <- reported %>%
  pivot_longer(-reported_date, names_to = "category", values_to = "case") 
# To make the reported data tidy by summarizing 3 types of cases into the "category" column
reported_long$category <- str_to_sentence(reported_long$category)
# Capitalize the first letters of each value
reported_long$category <- factor(reported_long$category, 
                                 levels = c("Active", "Recovered", "Deceased")) 
# To factor the category to make them appropriately ordered
reported <- reported_long
```

\newpage
## Data visualization

```{r cases_vis, echo=TRUE}
reported %>%
  ggplot(aes(x = reported_date, y = case, fill = category)) +
  scale_x_date(labels = scales::date_format("%d %b %y"), 
               limits = c(date("2020-01-01"), date("2021-01-31"))) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 2000)) +
  labs(title = "Cases reported by day in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x = "Date",
       y = "Case count",
       caption = str_c("Created by: Shiqi Liu for STA303/1002, U of T\n", 
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", 
                       date_daily[1,1])) +
  theme(legend.title = element_blank(), legend.position = c(0.15, 0.80)) +
  scale_fill_manual(values = c("#003F5C", "#86BCB6", "#B9CA5D"), 
                    breaks = c("Active", "Recovered", "Deceased"))
```

\newpage
# Task 2: Outbreak type
## Data wrangling


```{r outbreak_dw, echo=TRUE}
outbreak <- outbreak_raw
outbreak$episode_week <- date(outbreak$episode_week) 
# To make the values in the episode_week column in date format
outbreak$outbreak_or_sporadic <- str_replace_all(outbreak$outbreak_or_sporadic, 
                                                 "OB Associated", "Outbreak associated") 
# To change the name of the string values in the outbreak_or_aporadic column to match the figure presentation
weekly_case = summarise(group_by(outbreak, episode_week), total_cases = sum(cases)) 
# Create a new variable total_cases indicating the total number of cases in the episode week
outbreak <- left_join(outbreak, weekly_case) 
# To combine the weekly_case data with the outbreak data by the common varibale episode_week
outbreak$outbreak_or_sporadic <- factor(outbreak$outbreak_or_sporadic, 
                                        levels = c("Sporadic", "Outbreak associated")) 
# To factor the outbreak_or_sporadic variable values to make them appropriately ordered
```

\newpage
## Data visualization

```{r outbreak_vis, echo=TRUE}
outbreak %>% 
  ggplot(aes(x = episode_week, y = cases, fill = outbreak_or_sporadic)) +
  scale_x_date(labels = scales::date_format("%d %b %y"), 
               limits = c(date("2020-01-01"), date("2021-01-31"))) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, max(outbreak$total_cases))) +
  labs(title = "Cases by outbreak type and week in Toronto, Canada",
       subtitle = "Confirmed and probable cases",
       x = "Date",
       y = "Case count",
       caption = str_c("Created by: Shiqi Liu for STA303/1002, U of T\n", 
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", 
                       date_daily[1,1])) +
  theme(legend.title = element_blank(), legend.position = c(0.15, 0.8)) +
  scale_fill_manual(values = c("#86BCB6", "#B9CA5D"), 
                    breaks = c("Sporadic", "Outbreak associated"))
```

\newpage
# Task 3: Neighbourhoods
## Data wrangling: part 1

```{r nbhood_dw_1, echo=TRUE}
income_raw <- nbhood_profile %>%
  filter(`_id` == 1143) 
# The row number corresponding to the percentage of 18 to 64 year-olds classified as low income is 1143
income <- income_raw %>%
  pivot_longer(-c(1:5), names_to = "neighbourhood_name",
               values_to = "percentage") %>% 
  # No change for the first 5 columns
  mutate(percentage = parse_number(percentage)) 
# To make sure the percentages are stored as numbers
```

## Data wrangling: part 2

```{r nbhood_dw_2, echo=TRUE}
nbhood <- nbhoods_shape_raw %>%
  mutate(neighbourhood_name = str_remove(AREA_NAME,
         "\\s\\(\\d+\\)$")) %>% 
  # To remove the number in parenthese in the AREA_NAME variable, and create a new variable neighbourhood to the cleaned names
  mutate(neighbourhood_name = case_when(neighbourhood_name == "North St.James Town" ~ 
                                          "North St. James Town",
                                        neighbourhood_name == "Weston-Pellam Park" ~ 
                                          "Weston-Pelham Park",
                                        neighbourhood_name == "Cabbagetown-South St.James Town" ~ 
                                          "Cabbagetown-South St. James Town",
                                        TRUE ~ neighbourhood_name)) 
# To make sure the neighbourhoods name are correctly matched
nbhood1 <- left_join(nbhood, income, by = "neighbourhood_name")
nbhood2 <- left_join(nbhood1, nbhood_raw, by = "neighbourhood_name")
nbhoods_all <- nbhood2 %>%
  rename(rate_per_100000 = rate_per_100_000_people) 
# Rename the case rate variable
```

## Data wrangling: part 3

```{r nbhood_dw_3, echo=TRUE}
med_inc <- median(nbhoods_all$percentage, na.rm = TRUE) 
# To calculate the median perceantage of 18 to 64 year-olds who are classified as low income
med_rate <- median(nbhoods_all$rate_per_100000, na.rm = TRUE) 
# To calculate the median case rate per 100,000 people
nbhoods_final <- nbhoods_all %>%
  mutate(nbhood_type = case_when(percentage >= med_inc & rate_per_100000 >= med_rate ~ 
                                   "Higher low income rate, higher case rate",
                                 percentage >= med_inc & rate_per_100000 < med_rate ~ 
                                   "Higher low income rate, lower case rate",
                                 percentage < med_inc & rate_per_100000 >= med_rate ~ 
                                   "Lower low income rate, higher case rate",
                                 percentage < med_inc & rate_per_100000 < med_rate ~ 
                                   "Lower low income rate, lower case rate"))
```

\newpage
## Data visualization

```{r neighbourhood_graphs_1, fig.height=4, echo=TRUE}
ggplot(data = nbhoods_final) + 
  geom_sf(aes(fill = percentage)) + 
  # To color the figure by the low income percentage
  theme_map() +
  scale_fill_gradient(name = "% low income", low = "darkgreen", high = "lightgrey") + 
  labs(title = "Percentage of 18 to 64 year olds living in a low income family (2015)",
       subtitle = "Neighbourhoods of Toronto, Canada",
       caption = str_c("Created by: Shiqi Liu for STA303/1002, U of T\n", 
                       "Source: Census Profile 98-316-X2016001 via OpenData Toronto\n", 
                       date_nbhood[1,1])) +
  theme(legend.position = "right")
```

\newpage

```{r neighbourhood_graphs_2, fig.height=4, echo=TRUE}
ggplot(data = nbhoods_final) + 
  geom_sf(aes(fill = rate_per_100000)) + 
  # To color the figure by the case rate per 100,000 people
  theme_map() +
  scale_fill_gradient(name = "Cases per 100,000 people", low = "white", high = "darkorange") + 
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: Shiqi Liu for STA303/1002, U of T\n", 
                       "Source: Ontario Ministry of Health, Integrated Public Health Information System and CORES\n", 
                       date_nbhood[1,1])) +
  theme(legend.position = "right")
```

\newpage

```{r neighbourhood_graphs_3, fig.height=4, echo=TRUE}
ggplot(data = nbhoods_final) + 
  geom_sf(aes(fill = nbhood_type)) + # To color the figure by combining both the low income percentage and the case rate
  theme_map() +
  scale_fill_brewer(palette = "Set1", name = "% of 18 to 64 year-olds in \n low income families and \n COVID-19 case rates") + 
  labs(title = "COVID-19 cases per 100,000, by neighbourhood in Toronto, Canada",
       caption = str_c("Created by: Shiqi Liu for STA303/1002, U of T\n", 
                       "Income data source: Census Profile 98-316-X2016001 via OpenData Toronto\n", 
                       "COVID data source : Ontario Ministry of Health, Integrated Public\n Health Information System and CORES\n", 
                       date_nbhood[1,1])) +
  theme(legend.position = "right")
```




```{r, eval = FALSE}
# This chunk of code helps you prepare your assessment for submission on Crowdmark
# This is optional. If it isn't working, you can do it manually/take another approach.

# Run this chunk by hand after knitting your final version of your pdf for submission.
# A new file called 'to_submit' will appear in your working directory with each page of your assignment as a separate pdf.

# Install the required packages
if(!match("staplr", installed.packages()[,1], nomatch = FALSE))
  {install.packages("staplr")}

# Don't edit anything in this function
prep_for_crowdmark <- function(pdf=NULL){
  # Get the name of the file you're currently in. 
  this_file <- rstudioapi::getSourceEditorContext()$path
  pdf_name <- sub(".Rmd", ".pdf", sub('.*/', '', this_file))
  
  # Create a file called to_submit to put the individual files in
  # This will be in the same folder as this file is saved
  if(!match("to_submit", list.files(), nomatch = FALSE))
    {dir.create("to_submit")}
 
  # Split the files
  if(is.null(pdf)){
  staplr::split_pdf(pdf_name, output_directory = "to_submit", prefix = "page_")} else {
    staplr::split_pdf(pdf, output_directory = "to_submit", prefix = "page_") 
  }
}

prep_for_crowdmark()

```